### ISSUE TITLE
Localizing Theia

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#10188]
This is issue tracks the ongoing effort (and eventual problems) for localizing Theia.

- [x] https://github.com/eclipse-theia/theia/pull/9538
- [ ] https://github.com/eclipse-theia/theia/pull/10084
- [ ] https://github.com/eclipse-theia/theia/pull/10087
- [ ] https://github.com/eclipse-theia/theia/pull/10106
- [ ] https://github.com/eclipse-theia/theia/pull/10187

**Comment by vince-fugnitto** [comment]
@msujew I believe the last two items in the list are now merged, is anything missing to complete the epic?
