### ISSUE TITLE
Improve and simplify commands/menus/keybindings contributions

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#105]
- [ ] ~~remove 1-n between command and handlers, by simply let put all the functions of CommandHAndler into Command~~
- [ ] ~~remove keybinding context stuff and totally rely on command’s isEnabled()~~
- [x] allow passing args to commands, as varargs
- [ ] use `T | Promise<T>` for `execute`, `isEnabled` and so on - https://github.com/theia-ide/theia/issues/435
- [ ] move `isVisible` to a menu item
- [x] allow dynamic menu contributions
- [ ] expose API to build menus from `MenuModelRegistry`, like `findGroup`
- [x] consider introducing a composite contribution which allows contributing commands, menus and keybindings at once - one can implement all contributions with one class
- [x] move keybindings to browser since it relies on dom events - https://github.com/theia-ide/theia/issues/434
- [x] rename modifiers: https://github.com/theia-ide/theia/issues/458

Add more points if I miss something.

**Comment by svenefftinge** [comment]
We should keep the KeybindingContext (and registry). It nicely allows to contribute contextual keybindings, especially for users through keymaps.
