### ISSUE TITLE
Backport issues to 1.37.2

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12518]
List of fixes to be back-ported to 1.37.2

- [x]  https://github.com/eclipse-theia/theia/pull/12411
- [x]  https://github.com/eclipse-theia/theia/pull/12477
- [x] Telemetry API https://github.com/eclipse-theia/theia/pull/12453
- [x] https://github.com/eclipse-theia/theia/pull/12489
- [x] https://github.com/eclipse-theia/theia/pull/12483
   - [x] https://github.com/eclipse-theia/theia/pull/12554
- [x] Upgrade VS Code **version** and **built ins** to 1.77
   - [x] https://github.com/eclipse-theia/theia/pull/12516
   - [x] Built in's => This is not a code change, but we'll wait with publishing the release until @marcdumais-work gives the word it's ready
- #12409 => this one is already in 1.37.0, so no action necessary.
- [x] #12514
- [x] https://github.com/eclipse-theia/theia/issues/12521

**Comment by tsmaeder** [comment]
Previous release: https://github.com/eclipse-theia/theia/issues/12479

**Comment by rschnekenbu** [comment]
Hi @tsmaeder, should there be in this list the 3 other proposed APIs issues, as required for builtins under version 1.77.2?
- #12520
- #12522 
- #12523

**Comment by alvsan09** [comment]
Hi @tsmaeder , 
I think we should consider this:
https://github.com/eclipse-theia/theia/pull/12482

**Comment by tsmaeder** [comment]
@marcdumais I would think we should cherry-pick https://github.com/eclipse-theia/theia/pull/12512/files, as well, right?

**Comment by tsmaeder** [comment]
- [ ] https://github.com/eclipse-theia/theia/pull/12555

**Comment by marcdumais-work** [comment]
The built-ins 1.77.0 were/are ready :) - updating the description to reflect this.

**Comment by JonasHelming** [comment]
@tsmaeder This is done isn't it?
