### ISSUE TITLE
Improvmenents for Dog-Fooding Theia

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12693]
This epic collects improvements to enable the use of Theia blueprint for developing Theia itself. 

#### Impediments
- [ ] https://github.com/eclipse-theia/theia-blueprint/issues/278
- [ ] https://github.com/eclipse-theia/theia-blueprint/issues/235
- [ ] https://github.com/eclipse-theia/theia/issues/12355 
(@tsmaeder: Not a nitpick, IMO, since gitlens is part of my workflow and it's hard to use if you don't see the icons)
#### Nitpicks
- [ ] https://github.com/eclipse-theia/theia-blueprint/issues/277

**Comment by tsmaeder** [comment]
Btw: when I write "blockers" the meaning is "blocking adoption of Theia as the main dev platform for Theia", not that you can't use Theia at all.
