### ISSUE TITLE
Improve notebook UI/UX

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#12863]
After merging #12442, there are still quite a few issues to be tackled related to the UI/UX of the notebook support:

- [ ] `files.autoSave` does not seem to be respected by the notebook editor widget/model.
- [ ] Closing a dirty notebook editor widget does not prompt to save the widget.
- [x] Switching file-icon themes is not respected by the notebook
- [x] Improve notebook scrolling:

https://github.com/eclipse-theia/theia/assets/40359487/dbf87893-bb3c-4664-8016-041a04f89ac3

- [x] Improve toolbar items for the notebook https://github.com/eclipse-theia/theia/pull/13334
  - Items are not rendered similarly to the rest of the application, rounded border
  - The tooltip for the items do not display their full name similarly to VS Code
- [x] "Select Another Kernel" should allow to go back in the quick-input prompt

Feel free to use this as a general tracker, and add more issues here.

**Comment by jbicker** [comment]
[Improved](https://github.com/eclipse-theia/theia/pull/13334) the toolbar items. 
Will look into the scrollbar issue now.
