### ISSUE TITLE
Improve start-up performance

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#12924]
This is an umbrella issue for coordinating different work streams to improve the start-up performance of Theia, both for Electron and Browser deployment. At the moment, the following topics / PRs are work in progress:

- *Gathering of measurements*
  - [X] https://github.com/eclipse-theia/theia/pull/12812 and make them available via `/metrics`
  - [X] Run end-to-end tests periodically and create a [report showing how the measurements evolve over time](https://eclipse-theia.github.io/theia-e2e-test-suite/performance/) (see also https://github.com/eclipse-theia/theia-e2e-test-suite)
  - [ ] Extend the end-to-end tests above to also run with Electron (blocked by https://github.com/eclipse-theia/theia/pull/12207)
  - [ ] For production builds the performance logging is broken as it relies on the class names. We should at least document how to disable class name optimization in webpack.
- *Backend improvements*
  - [X] Between v1.38 and v1.40 the backend start-up has improved impressively by > 50 % (largely enabled by the [backend bundling](https://github.com/eclipse-theia/theia/issues/12391))
  - [ ] Defer i18n initialization (see also https://github.com/kittaakos/arduino-ide/commit/b78800571348c27a36536b3201bffc8f776aebe5)
- *Frontend improvements*
  - [ ] Reducing awaits in the frontend seem to enable a performance gain of ~400-1000ms of about 2500ms startup overall (see also [work in progress PR](https://github.com/eclipsesource/theia/pull/90))
- *VS Code Extensions*
  - [ ] First measurements indicate that interpreting some declarative API is rather slow, but this needs to be confirmed
- *Electron*
  - [ ] https://github.com/eclipse-theia/theia/pull/12897

Please feel free to add your topics or comment on any of the lsited streams of work. The goal of this GH issue is to collect and coordinate the work towards performance improvements of several teams.

**Comment by sdirix** [comment]
There are two related issues listed in the old epic #9869 which could be added to the list here:
 - https://github.com/eclipse-theia/theia/issues/9722
 - https://github.com/eclipse-theia/theia/issues/9868
