### ISSUE TITLE
Theia IDE Beta Epic

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#13192]
This epic collects improvements for the Theia IDE Beta version

#### Blockers
- [x] https://github.com/eclipse-theia/theia/issues/12708
- [ ] #12757
- [x] https://github.com/eclipse-theia/theia-blueprint/issues/291
- [ ] https://github.com/eclipse-theia/theia-blueprint/issues/317
#### Impediments
- [x] #12821
- [ ] https://github.com/eclipse-theia/theia/issues/12701
- [x] https://github.com/eclipse-theia/theia/issues/12823
- [ ] https://github.com/eclipse-theia/theia-blueprint/issues/281
- [x] https://github.com/eclipse-theia/vscode-builtin-extensions/issues/123
Running an extension is often used when creating a reproducer for an API issue
- [ ] https://github.com/eclipse-theia/theia/issues/12707
- [x] https://github.com/eclipse-theia/theia/issues/12355 
- [ ] https://github.com/eclipse-theia/theia/issues/13046
- [ ] https://github.com/eclipse-theia/theia/issues/13047
- [ ] https://github.com/eclipse-theia/theia/issues/13108
- [ ] https://github.com/eclipse-theia/theia/issues/13086
- [ ] https://github.com/eclipse-theia/theia/issues/9382
- [x] https://github.com/eclipse-theia/theia/issues/13164
#### Nitpicks
- [x] https://github.com/eclipse-theia/theia-blueprint/issues/277
- [ ] https://github.com/eclipse-theia/theia/issues/12741
- [ ] #12907

**Comment by eneufeld** [comment]
@JonasHelming please consider adding https://github.com/eclipse-theia/theia/issues/11955 as this is very annoying for debugging

**Comment by tsmaeder** [comment]
Recently closed issues: 

- [x] #15077 
- [x] #15145
- [x] #15137
- [x] https://github.com/eclipse-theia/theia/issues/15296
- [x] #15171
- [x] https://github.com/eclipse-theia/theia/issues/15426
- [x] [blocked] https://github.com/eclipse-theia/theia/issues/15417
- [x] https://github.com/eclipse-theia/theia/issues/15274
- [x] https://github.com/eclipse-theia/theia/issues/15273
- [x] https://github.com/eclipse-theia/theia/issues/15370 
- Issues related to hiding editors
   - [x] https://github.com/eclipse-theia/theia/issues/15498
   - [x] https://github.com/eclipse-theia/theia/issues/15497
   - [x] https://github.com/eclipse-theia/theia/issues/15496

**Comment by ndoschek** [comment]
Closing this, it has been replaced by a [GH project table view](https://github.com/orgs/eclipse-theia/projects/4/views/1)
