### ISSUE TITLE
[vscode] proposed API evolution and menu declarations between 1.89 and 1.90 (WIP)

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#13753]
### Sources
- **commit ref for tags** 
   - 1.89.0: [b58957e](https://github.com/microsoft/vscode/commit/b58957e67ee1e712cebf466b995adf4c5307b2bd)
   - main (not yet released): [89de5a8](https://github.com/microsoft/vscode/commit/89de5a8d4d6205e5b11647eb6a74844ca23d2573)

- **command used**
  - `git difftool -d b58957e..89de5a8 -- src/vscode-dts/` on vscode repo
  - command: `git submodule foreach "grep -irn enabledApiProposals --include=package.json | cut -d ':' -f 1 | xargs jq --raw-output '{filename: input_filename, enabledApiProposals: .enabledApiProposals}'" > ./vscode-builtins-enabled-proposals-1.90.0.txt` on vscode-builtin-extensions repo, on tag 1.90.0 (currently on branch 1.90)
  - `git difftool -d b58957e..89de5a8 -- src/vs/workbench/services/actions/common/menusExtensionPoint.ts` on vscode repo

### Evaluation
- [x] vscode.proposed.attributableCoverage.d.ts: new with 1.90. Only used in vscode self host test plugin.
- [x] vscode.proposed.chatParticipant.d.ts. Removed as a public API. See #13756. 
- [x] vscode.proposed.chatParticipantAdditions.d.ts: Updated (parts of it being public). Not used in builtins.
- [x] vscode.proposed.chatParticipantPrivate.d.ts: New in 1.90. Additional properties for public API. Not used except in tests.
- [x] vscode.proposed.chatProvider.d.ts: updated in 1.90. Not used in builtins.
- [x] vscode.proposed.chatVariableResolver.d.ts: updated in 1.90. Not used in builtins except tests.
- [x] vscode.proposed.debugFocus.d.ts: removed as becoming public API (see #13758)
- [x] vscode.proposed.defaultChatParticipant.d.ts: updated in 1.90, not used in builtins except tests.
- [x] vscode.proposed.editorHoverVerbosityLevel.d.ts: updated in 1.90. not used in builtins.
- [x] vscode.proposed.embeddings.d.ts: new in 1.90. not used in builtins except tests.
- [x] vscode.proposed.interactive.d.ts: mostly cleaned in 1.90, to disapear in incoming versions. not used in builtins except tests
- [x] vscode.proposed.languageModels.d.ts: removed as becoming public API (see #13756)
- [x] vscode.proposed.languageModelSystem.d.ts: new in 1.90. not used in builtins.
- [x] vscode.proposed.resolvers.d.ts: updated in 1.90, not used except for testing
- [x] vscode.proposed.speech.d.ts: updated in 1.90. Not used in builtins
- [x] vscode.proposed.testObserver.d.ts: updated in 1.90. not used in builtins except tests and vscode-selfhost-test-extension.
- [x] vscode.proposed.testPreserveFocus.d.ts: deleted as now a public API. See #13759

**Comment by rschnekenbu** [comment]
closing as it is a documentation task.
