### ISSUE TITLE
Theia AI Epic

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#14119]
This epic provides an overview of upcoming improvements and features for Theia AI and the AI integration in the Theia IDE:

# High prio
- [x] #14133 
- [x] When closing and reopening the chat, experimental warning is shown again	(150)
- [x] #14128
- [x] #14185
- [x] #14180
- [x] #14161
- [x] #14167
- [x] #14856
- [x] #14205
- [x] #14174
- [x] #14164
- [x] #14201
- [x] #14208
- [ ] #14209
- [x] #14236
- [x] #14768
# Medium prio
- [x] #14613
- [x] #14512
- [x] #14485
- [x] #14469
- [x] #14471
- [x] #14464
- [x] #14460
- [x] #14423
- [x] #14411
- [x] #14392
- [x] Invalid Response Format error	(148)
- [x] #14183
- [x] Error is thrown regarding templates (134)
- [x] Error is thrown in backend (extensions) in regards to ChatView (135)
- [x] Responses are recorded multiple times (136)
- [x] #14252
- [x] #14245
- [x] #14322
- [x] Consider limiting the scope of tool functions (107)
- [x] #14286
- [x] Chat view conflicts with vim extension in Theia IDE (133)
- [x] Response Part Renderer for `code-diff` (20)
- [x] #14313
- [x] #14312
- [x] User context aware chat agent (159)
- [x] Terminal Chat Provider (129)
- [x] Response Part Renderer to execute terminal commands (52)
- [x] Edit user prompt (102)
- [x] Prompt debugging support (103)
- [x] Offer a way to clear history (139)
- [x] Description of Agents in the Agent Configuration is cut (123)
- [x] Explicitly support multi-turn sessions (162)
- [x] Support attaching arbitrary blobs of data to responses (163)
- [ ] https://github.com/eclipse-theia/theia/issues/14324
- [x] #14329
- [x] #14448
- [x] Workspace functions ignore multiple workspaces
- [x] #14441
- [ ] #14452
- [ ] https://github.com/eclipse-theia/theia/issues/14543#event-15452436624

**Comment by JonasHelming** [comment]
All open issues transfered to here: #15068
