### ISSUE TITLE
Dev container support Epic

### ISSUE THREAD

**Issue by sgraband** [eclipse-theia/theia#14294]
This epic collects improvements relevant for the Dev container support in Theia.

### Tickets:

- [ ] https://github.com/eclipse-theia/theia/issues/14291
- [ ] https://github.com/eclipse-theia/theia/issues/14292
- [ ] https://github.com/eclipse-theia/theia/issues/14293
- [ ] https://github.com/eclipse-theia/theia/issues/14137

**Comment by tsmaeder** [comment]
@sgraband  https://github.com/eclipse-theia/theia/issues/14307
