### ISSUE TITLE
Build component

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#183]
As an IDE user: 
- I want to be able to build the source code of my project (for whatever supported programming language), and obtain an executable file or package, that can later be run in a proper runtime environment.
- I want to be able to build multiple “targets”, build the last target with a keyboard shortcut (or possibly be able to define a keyboard shortcut for each target)
- I want to be notified of the status of the build (started, finished successfully or not)
- I want the build errors to be shown in the Problems View and the editor

As an extension developer
- I want to be able to contribute my own “build components”, so that I can extend Theia to support new programming languages
- I want my components be able to register to receive build output, so that I can extract interesting information from it (e.g. C/C++ language extension might need gcc output to figure-out includes/macros information)

Tasks: 
- [ ] Have a configuration file that describes which command to run for a given configuration name: 3
- [ ] Add a command to build a specific configuration: 2
- [ ] Add the ability to specify an error parser for a given configuration. Design extension point, API and reading of config file: 5
- [ ] Add a an error parser for GCC-like errors, warnings, etc. (Possibly an existing one can be reused): 5
- [ ] Report errors in Problems view: 5

**Comment by svenefftinge** [comment]
I think compilers and build scripts are usually processes that have to be managed. Some keep running for longer watching for file changes, others run one-off.
Could we not do this through #184?

For the notifications and the error, I suggest to allow extensions to contribute console log parsers. They get the full output stream from the process and could do what every they want (e.g. send notification and create markers).

Multiple targets could map to multiple launch configs.

**Comment by marcdumais-work** [comment]
Hi @svenefftinge - Agreed, launch/debug configurations can be handled separately from build.

**Comment by marcdumais-work** [comment]
Hi @svenefftinge 

I think I originally misinterpreted your comment above. When you said "Could we not do this through #184?", did you mean to suggest that we could/should generalize build processes, to also handle other types of processes, like launching? 

We have had some recent discussions about doing something like that, taking inspiration from vscode. We are thinking that we could have a "TaskProcess" derived from Antoine's TerminalProcess, that optionally can have a console log parser attached, designed to catch specific errors/warnings from the terminal's output. When the user configures a Task to be executed, they could select one console log parser to be used with it.

**Comment by svenefftinge** [comment]
yes, I wanted to suggest something in that direction.

**Comment by marcdumais-work** [comment]
Replacing this feature, in the Theia BETA Milestone, by Task (#686) - Tasks are more generic, meant to execute anything. They can also be used to start builds. Later-on we can refine the Task extension to be more build-friendly.

**Comment by vince-fugnitto** [comment]
> Replacing this feature, in the Theia BETA Milestone, by Task (#686)

Cleanup, the issue can be closed as it has been replaced with the idea of `tasks` which is currently implemented.
