### ISSUE TITLE
[plug-in] Harden and polish the Plug-in System

### ISSUE THREAD

**Issue by ashumilova** [eclipse-theia/theia#2269]
The first implementation phase of Plug-in system has been finished, and it included all the essential APIs needed for the start to interact with Theia components from plug-ins.

Just to revise, they are the following: Preferences, Commands, Notifications, Editor, Status bar, Terminal, Open/Save/Input Dialogs and Output channel APIs. Also new namespace - environment was introduced.

The next step is to make our Plug-ins API model tougher and more clearly defined and used.

It could be divided in following sections, which could also be split in separate epics.

### Fill-in the missing pieces:
There the APIs, that are still missing, and the list could really increase during work being in progress.
(_Note: the order is not prioritized_)
- [x] Workspace Folder Pick API https://github.com/theia-ide/theia/issues/2337
- [x] Tree + Tree view + Tree data provider https://github.com/theia-ide/theia/issues/2782
- [x] File system watcher creator (needed for LS)
- [x] Find files
- [x] Apply edit (workspace) (needed for LS) https://github.com/theia-ide/theia/issues/2784
- [ ] Configuration and Defaults contribution
- [x] Languages https://github.com/eclipse/che/issues/10206 https://github.com/theia-ide/theia/issues/2341
- [ ] Debugger API (bigger)
- [x] Extensions API https://github.com/theia-ide/theia/issues/2561
- [x] [WebView API ](https://code.visualstudio.com/docs/extensions/webview)

Low priority:
- [x] syntax highlight APIs
- [ ] Register task provider
- [x] Register file system provider https://github.com/theia-ide/theia/issues/2861
- [ ] Version control system management APIs

Nice to have
- [ ] Themes management
- [ ] Snippets
- [x] Menu Plugin API https://github.com/theia-ide/theia/issues/2785
- [x] Register text document content provider https://github.com/theia-ide/theia/issues/2786
- [x] Key bindings https://github.com/theia-ide/theia/issues/2783
- [x] API endpoint for window.showTextDocument theia-ide/theia#2801
- [x] API endpoint window.withProgress theia-ide/theia#2802

### Plug-in Model documentation
- [ ] Provide the detailed documentation on all the existing APIs
- [ ] Provide the tutorial for plugin writers

### Move existing extensions to plugin model
- [x] SSH extension
- [x] GitHub extension

**Comment by AlexTugarev** [comment]
can this be considered too? https://github.com/theia-ide/theia/issues/2258

**Comment by ashumilova** [comment]
@AlexTugarev  yes, sure

**Comment by vince-fugnitto** [comment]
I believe this issue is now outdated, and we can safely close. We have other "epics" which describe improvements to the plugin-system and vscode support.
