### ISSUE TITLE
[vscode] support activation events

### ISSUE THREAD

**Issue by dehru** [eclipse-theia/theia#4199]
Hello, I've got a vscode extension running in theia version "next" (  "version": "0.4.0-next.e2f3ec66" ).  But there's a slight difference in when the activation() lifecycle method gets called.  

The vscode extension was built with "vscode": "1.1.28", and has this info in it's package.json
```
        "activationEvents": [
		"onCommand:extension.execute-command"
	],
	"main": "./out/extension.js",
	"contributes": {
		"commands": [{
			"command": "extension.execute-command",
			"title": "Hello Execute Command"
		}]
	},
```

And a very simple extension.ts that looks like this.
```
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	console.log('activate called');
	vscode.commands.executeCommand('setContext', 'thisContext', true);
}

export function deactivate() {}
```

When running in vscode, the activate method is not called until the command is actually triggered through the vscode command palette.

When running inside theia, the activate method is called as soon as the browser is connected / opened.  This makes debugging the activate method a little more challenging.  And could lead to different behavior with vscode extensions.

**Comment by akosyakov** [comment]
Activation events are not supported yet, VS Code extensions are activated eagerly for now.

**Comment by dehru** [comment]
I'm looking for suggestions for how to I might hook into a theia lifecycle events, to allow me to get around some issues I'm having with eager activation of vscode extensions.  

In my project, I need to show or hide certain commands in the CommandPalette, or in the right click context menus, depending on what the context is.

Is there a way that I can use events/context to show / hide things in the command palette or other menus dynamically?

Thank you for any input you might have.

**Comment by akosyakov** [comment]
Hit it again trying to debug LS process of vetur VS Code extensions. It's really hard since debug configuration rely on lazy loading of extensions :(

**Comment by akosyakov** [comment]
For rust extension, it is necessary to fix it, otherwise it starts contributing UI elements regardless whether rust project opened or not.

**Comment by akosyakov** [comment]
- [ ] `onWebviewPanel` https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/api/browser/mainThreadWebview.ts#L72
- [ ] `onView` https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/browser/parts/views/customView.ts#L499
- [ ] `onDebug`, `onDebugAdapterProtocolTracker`, `onDebugResolve`, `onDebugInitialConfigurations` https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L434 and https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/contrib/debug/browser/debugService.ts#L257
- [ ] `onCommand:workbench.action.tasks.runTask`
https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/contrib/tasks/browser/taskQuickOpen.ts#L43 and https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1112
- [ ] `*` - after initial contributions are initialized
https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/services/commands/common/commandService.ts#L39
- [ ] `onCommand`
https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/services/commands/common/commandService.ts#L53
- [ ] `onFileSystem`
https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L78
- [ ] `onUri`
https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/services/extensions/common/inactiveExtensionUrlHandler.ts#L136
- [ ] `onLanguage`
https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/services/mode/common/workbenchModeService.ts#L155
- [ ] `onSearch`
https://github.com/microsoft/vscode/blob/893bf4ea1f8c158125746c3fe959ef4e23883282/src/vs/workbench/services/search/common/searchService.ts#L98
- [ ] for forward compatibility fallback to `*` and report unknown activation event as an error to the console

**Comment by akosyakov** [comment]
Docs https://code.visualstudio.com/api/references/activation-events

**Comment by akosyakov** [comment]
For `onView` event  we need to integrate new view containers in the plugin system first, since it should be fired on expansion on the view. If we do it now we need to reimplement it later again.

**Comment by akosyakov** [comment]
I will stop working on it. `onView` and `onWebview` require substantial refactoring in the plugin system to integrate them properly with the shell. Regarding the rest of events i have not seen them in practice used a lot and will wait for some extension to come around.

**Comment by akosyakov** [comment]
`onView` is covered in https://github.com/theia-ide/theia/pull/5665

**Comment by akosyakov** [comment]
`onWebviewPanel` is covered in https://github.com/eclipse-theia/theia/pull/6465, but activation event is not listed as a supported, we should do it

**Comment by akosyakov** [comment]
`onFileSystem` is covered in https://github.com/eclipse-theia/theia/pull/7908

**Comment by tsmaeder** [comment]
Closing this omnibus issue, as we generally support activation events.

**Comment by tsmaeder** [comment]
The list is at least partially out of date ("onRenderer"). If we have missing activation events, they should be tracked by separate issues and linked to the VS Code API version where they appear. This old issue is not useful, IMO.

**Comment by alvsan09** [comment]
> The list is at least partially out of date ("onRenderer"). If we have missing activation events, they should be tracked by separate issues and linked to the VS Code API version where they appear. This old issue is not useful, IMO.

Unfortunately the activation events are independent of the `vscode` API, and would therefore need a parallel tracking, 
a similar case where we would need parallel tracking would be `vscode` contribution points.
