### ISSUE TITLE
Upgrade to the latest Monaco

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-theia/theia#6900]
VS Code has replaced Octicons with Codicons https://github.com/microsoft/vscode/pull/82729
We have to upgrade to the latest Moncao in order to get this support. See https://github.com/eclipse-theia/theia/issues/5412#issuecomment-574072885

closes #5412

##### Sub tasks:
- [x] upgrade [vscode-ws-jsonrpc](https://github.com/TypeFox/vscode-ws-jsonrpc) to the `5.0.0` version of `vscode-jsonrpc` https://github.com/TypeFox/vscode-ws-jsonrpc/issues/17
- [x] upgrade [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to the latest Monaco version https://github.com/TypeFox/monaco-languageclient/issues/194
- [x] upgrade [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to the latest LSP version https://github.com/TypeFox/monaco-languageclient/issues/196
- [x] signatures alignment (signatures exist and matching in https://github.com/theia-ide/vscode/tree/standalone/0.19.x)
- [x] revert the hotfix for IME support https://github.com/eclipse-theia/theia/pull/6673 and check whether IME support is fixed in newer Monaco
  - the hotfix was reverted, but it's required more investigation why it doesn't work for Theia: https://github.com/eclipse-theia/theia/pull/6673#issuecomment-599999501
- [x] Upgrade Theia to LSP 6.0.0 and Monaco 0.19.3 https://github.com/eclipse-theia/theia/pull/7149

##### References:
- Migration Guidelines - https://github.com/eclipse-theia/theia/wiki/LSP-and-Monaco-integration#migration-guidelines
- https://github.com/eclipse-theia/theia/issues/5412#issuecomment-574502938

**Comment by azatsarynnyy** [comment]
@akosyakov as you usually do that upgrade and you have the experience, please direct us if there is anything more we need to consider except the Migration Guidelines.
We would be very grateful.

**Comment by akosyakov** [comment]
@azatsarynnyy The start will be to create a PR in monaco-languageclient which upgrades it to latest Monaco and LSP version. There also could be some PRs which has to be applied first. Would it be fine if I invite you and @RomanNikitenko as maintainers to this project that you can merge existing PRs if you need them?

**Comment by benoitf** [comment]
BTW should we move monaco language client to `eclipse-theia` or `theia-ide` org ?

**Comment by azatsarynnyy** [comment]
> Would it be fine if I invite you and @RomanNikitenko as maintainers to this project ...

@akosyakov sure

**Comment by akosyakov** [comment]
> BTW should we move monaco language client to eclipse-theia or theia-ide org ?

I don't know @svenefftinge ? generally, monaco-languageclient cares only to monaco and lsp, Theia just one of its consumer, there are other projects who don't care

**Comment by akosyakov** [comment]
@azatsarynnyy @RomanNikitenko I've invited you with admin privileges. The only thing which you cannot do is to publish official release, but whenever you merge something to master `next` version will be published.

Regarding to moving under theia-org, I'm not opposed if it makes it easier to contribute. But @svenefftinge should decided. It's pure TypeFox project.

**Comment by akosyakov** [comment]
We should for sure do the custom build of monaco from fork under theia-ide org this time, not from TypeFox. But that's later.

**Comment by akosyakov** [comment]
@azatsarynnyy Could you add as a sub-task to revert https://github.com/eclipse-theia/theia/pull/6673 and check whether IME support was fixed in newer Monaco please?

**Comment by akosyakov** [comment]
I've added a first monaco api test here for resolveKeybinding api which was exposed in Jan: https://github.com/eclipse-theia/theia/blob/99209e4d62067e3f5e303efa317188302953a232/examples/api-tests/src/monaco-api.spec.js#L45 I would like to have more such tests ideally to cover all internally exposed api. It still won't be enough though we will need some tests from user perspective, i.e. that focus given properly or that on esc the reference pick widget is closed if it is closed.

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy Could you add as a sub-task to revert #6673 and check whether IME support was fixed in newer Monaco please?

@akosyakov added
