### ISSUE TITLE
API Gap theia master vs. VS Code 1.55.2

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#9863]
This bug tracks the differences between current master Theia VS Code API and VS Code 1.55.2

* [x] #9903 
* [x] #9965 
* [x] #9987
* [x] #9988 
* [x] #9989
* [x] #9991
* [x] #10002
* [x] #10003
* [x] #10004
* [x] #10005
* [x] #10006
* [x] #10008
* [x] #10009
* [x] #10011
* [x] #10023
* [x] #10024
* [x] #10025
* [x] #10026
* [x] #10027
* [x] #10028
* [x] #10029
* [x] #10030
* [x] #10031
* [x] #10033
* [x] #10200 
* [x] #8740
* [x] #10201
* [x] #11019
* [x] https://github.com/eclipse-theia/theia/issues/11127
* [x] https://github.com/eclipse-theia/theia/issues/11128
* [x] https://github.com/eclipse-theia/theia/issues/11129
* [x] https://github.com/eclipse-theia/theia/issues/11131
* [x] https://github.com/eclipse-theia/theia/issues/11132
* [x] https://github.com/eclipse-theia/theia/issues/11134
* [x] https://github.com/eclipse-theia/theia/issues/11140
* [x] https://github.com/eclipse-theia/theia/issues/11133
* [x] https://github.com/eclipse-theia/theia/issues/11138
* [x] https://github.com/eclipse-theia/theia/issues/11139
* [x] https://github.com/eclipse-theia/theia/issues/11143
* [x] https://github.com/eclipse-theia/theia/issues/11144
* [x] https://github.com/eclipse-theia/theia/issues/11145
* [x] https://github.com/eclipse-theia/theia/issues/11146
* [x] https://github.com/eclipse-theia/theia/issues/11147
* [x] https://github.com/eclipse-theia/theia/issues/11148
* [x] https://github.com/eclipse-theia/theia/issues/11149
* [x] #10662
* [x] https://github.com/eclipse-theia/theia/issues/10661
* [x]  https://github.com/eclipse-theia/theia/issues/11521

**Comment by tsmaeder** [comment]
Types:

AccessibilityInformation missing
AuthenticationProvider in theia-proposed.d.ts
AuthenticationProviderAuthenticationSessionsChangeEvent in theia-proposed.d.ts

CallHierarchyItem
* missing 'tags' field

CancellationError missing

CodeAction
* isPreferred missing
* disabled missing

CodeActionKind
* SourceFixAll missing

CodeActionProvider no type parameter T
* resolveCodeAction missing

CodeActionProviderMetadata
* documentation missing

CommentThread
* can reply missing

CompletionItemKind
* User missing
* Issue missing

ConfigurationScope missing
CustomDocumentOpenContext
* untitledDocumentData missing

**Comment by SriniBlrRaman** [comment]
Can you share the plan for addressing the API gap. Thanks.

**Comment by hzhang1902** [comment]
Really need debug.stopDebugging. It's strange to have startDebugging but not stop aye?

**Comment by vince-fugnitto** [comment]
> Really need debug.stopDebugging. It's strange to have startDebugging but not stop aye?

@hzhang1902 please feel free to provide a pull-request if you're interested :+1: 
`startDebugging` is supported, it likely only needs to be tweaked to follow the latest supported API (`v1.53.2`):

https://github.com/eclipse-theia/theia/blob/839607bfab3f823f668627225b8df4b36263b042/packages/plugin/src/theia.d.ts#L9753-L9763

**Comment by ndoschek** [comment]
> window
> 
> - createStatusBarItem: missing override with id parameter
> 

Fixed via https://github.com/eclipse-theia/theia/pull/10754 (issue: https://github.com/eclipse-theia/theia/issues/10696)

**Comment by lucas-koehler** [comment]
> StatusBarItem
>- id missing
>- name missing
>- backgroundColor missing

I added #11019 for these.

**Comment by colin-grant-work** [comment]
> TextDocumentChangeReason, LanguageStatusItem

I'm working on these as part of #10819.

**Comment by planger** [comment]
@tsmaeder I've added a couple of issues for the remaining 1.55.2 API gap and updated the notes of the vscode-theia-comparator accordingly for existing issues and the new ones I created [(see PR#24)](https://github.com/eclipse-theia/vscode-theia-comparator/pull/24).

In case you would like to update [your list above](https://github.com/eclipse-theia/theia/issues/9863#issuecomment-895086596) too, I guess it is easiest to go through the [diff of the PR](https://github.com/eclipse-theia/vscode-theia-comparator/pull/24/files).

As far as I checked all missing interfaces, there should now be an issue for everything that's still missing.

Thanks!

**Comment by tsmaeder** [comment]
Awesome, thx @planger

**Comment by planger** [comment]
@tsmaeder I believe there is actually another one for 1.55.2: https://github.com/eclipse-theia/theia/issues/11521
